Models/ErrorViewModel.cs
namespace TicketToDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Filters.cs
using Microsoft.VisualBasic;

namespace TicketToDo.Models
{
    public class Filters
    {
        public Filters(string filterstring)
        {
            FilterString = filterstring ?? "all-all";
            string[] filters = FilterString.Split('-');
            Due = filters[0];
            StatusId = filters[1];
            
        }

        public string FilterString { get; set; }
        public string Due { get; set; }
        public string StatusId { get; set; }

        public bool HasDue => Due.ToLower() != "all";
        public bool HasStatus => StatusId.ToLower() != "all";

        public static Dictionary<string, string> DueFilterValues => new Dictionary<string, string>
        {
            {"future", "Future"},
            {"past", "Past"},
            {"today", "Today"}
        };

        public bool IsPast => Due.ToLower() == "past";
        public bool IsFuture => Due.ToLower() == "future";
        public bool IsToday => Due.ToLower() == "today";

    }
}

Models/Status.cs
namespace TicketToDo.Models
{
    public class Status
    {
        public string? StatusId { get; set; }
        public string? Name { get; set; }
    }
}

Models/Ticket.cs
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

namespace TicketToDo.Models
{
    public class Ticket
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a name for the ticket.")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter a description for the ticket.")]
        public string? Description { get; set; }
        [Required(ErrorMessage = "Please enter a due date.")]
        public DateTime? DueDate { get; set; }

        [Required(ErrorMessage = "Please enter a sprint number.")]
        [Range(1, 50, ErrorMessage = "Spring number must be a number between 1 and 50.")]
        public int SprintNumber { get; set; }

        [Required(ErrorMessage = "Please enter a point value.")]
        [Range(1, 50, ErrorMessage = "Point Value must be a number between 1 and 50.")]
        public int PointValue { get; set; }

        [Required(ErrorMessage = "Please select a status")]
        public string? StatusId { get; set; }
        public Status? Status { get; set; }

        public bool Overdue => Status?.ToString() == "inprogress" && DueDate < DateTime.Today;

    }
}

Models/TicketContext.cs
using Microsoft.EntityFrameworkCore;

namespace TicketToDo.Models
{
    public class TicketContext : DbContext
    {
        public TicketContext(DbContextOptions<TicketContext> options) : base(options) { }

        public DbSet<Ticket> Tickets { get; set; } 
        public DbSet<Status> Statuses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Status>().HasData(
                new Status { StatusId = "todo", Name = "To Do" },
                new Status { StatusId = "inprogress", Name = "In Progress" },
                new Status { StatusId = "qa", Name = "Quality Assurance" },
                new Status { StatusId = "done", Name = "Done" }
                );

           modelBuilder.Entity<Ticket>().HasData(
                new Ticket { Id = 5, Name = "task", Description = "do this task", DueDate = new DateTime(2023, 12, 21), SprintNumber = 4, PointValue = 2, StatusId = "qa" }
                );
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using TicketToDo.Models;

namespace TicketToDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private TicketContext context;

        public HomeController(ILogger<HomeController> logger, TicketContext ticketContext)
        {
            _logger = logger;
            ticketContext = context;
        }
        //private variable for the database context, the constructor, and the first three action method
        
        

        public IActionResult Index(string id)
        {
            //create new Fitlers object, passing id paramter to its constructor
            var filters = new Filters(id);

            ViewBag.Filters = filters;
            ViewBag.Statuses = context.Statuses.ToList();
            ViewBag.DueFilters = Filters.DueFilterValues;

            //build query for ToDo ojbects and related Category and Status objects
            IQueryable<Ticket> query = context.Tickets
                .Include(t => t.Status);
            //use has properties of the Filters object to add WHERE clauses to the query if the user has selected filter critieria
            if (filters.HasStatus)
            {
                query = query.Where(t => t.StatusId == filters.StatusId);
            }
            if (filters.HasDue)
            {
                var today = DateTime.Today;
                if (filters.IsPast)
                    query = query.Where(t => t.DueDate < today);
                else if (filters.IsFuture)
                    query = query.Where(t => t.DueDate > today);
                else if (filters.IsToday)
                    query = query.Where(t => t.DueDate == today);
            }
            //sort the results by due date and colling the ToList() method
            var tasks = query.OrderBy(t => t.DueDate).ToList();
            //pass the collection of tasks to the view
            return View(tasks);
        }

        //add action method handles GET requests
        [HttpGet]
        public IActionResult Add()
        {
            //get list of category and status objects from the database and assigns these collections to the ViewBag
            ViewBag.Statuses = context.Statuses.ToList();
            return View();
        }

        //handle POST requests
        [HttpPost]
        public IActionResult Add(Ticket task)
        {
            string key = nameof(Ticket.Name);
            var val = ModelState.GetValidationState(key);
            if (val == ModelValidationState.Valid)
            {
                if (task.Name == "Jack")
                {
                    ModelState.AddModelError(key, "Don't use the name Jack as a name!");
                }
            }
            if (ModelState.IsValid)
            {
                //add the new ToDo object to the ToDos context collection and call the SaveChanges() method to update the databse
                context.Tickets.Add(task);
                context.SaveChanges();
                //redirectthe user back to the Home page, where the new taks now displays in the list of tasks
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Statuses = context.Statuses.ToList();
                return View(task);
            }
        }

        [HttpPost]
        public IActionResult Filter(string[] filter)
        {
            string id = string.Join('-', filter);
            return RedirectToAction("Index", new { ID = id });
        }

        [HttpPost]
        //[FromRoute]  tells MVC to look for its value in a route paramter, 
        public IActionResult Edit([FromRoute] string id, Ticket selected)
        {
            // Find the existing ticket in the context
            var existingTicket = context.Tickets.Find(selected.Id);

 

            if (selected.StatusId == null)
            {
                
                context.Tickets.Remove(existingTicket);
            }
            else
            {
                // Update the status of the existing ticket
                existingTicket.StatusId = selected.StatusId;
                context.Tickets.Update(existingTicket);
            }

            context.SaveChanges();

            return RedirectToAction("Index", new { ID = id });
        }

        [HttpPost]
        public IActionResult ChangeStatus(string id, string newStatus)
        {
            var task = context.Tickets.Find(id);
            if (task != null)
            {
                task.StatusId = newStatus;
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }


    }
}

Views/Shared/Components/StatusButtonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TicketToDo.Models;

namespace TicketToDo.Views.Shared.Components
{
    public class StatusButtonViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Status status)
        {
            return View(status.ToString(), status);
        }
    }

}

Views/Home/Add.cshtml
@model Ticket
@await Component.InvokeAsync("StatusButton", Status.ToDo)
@await Component.InvokeAsync("StatusButton", Status.InProgress)
@await Component.InvokeAsync("StatusButton", Status.QualityAssurance)
@await Component.InvokeAsync("StatusButton", Status.Done)


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<h2>New Ticket</h2>
<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description">Description:</label>
        <input asp-for="Description" class="form-control">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SprintNumber">Sprint Number:</label>
        <input asp-for="SprintNumber" class="form-control">
        <span asp-validation-for="SprintNumber" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PointValue">Point Value:</label>
        <input asp-for="PointValue" class="form-control">
        <span asp-validation-for="PointValue" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DueDate">Due:</label>
        <input type="text" asp-for="DueDate" class="form-control">
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StatusId">Status:</label>
        <select asp-for="StatusId" class="form-control" asp-items="@(new SelectList(ViewBag.Statuses, "StatusId", "Name"))">
            <option value=""></option>
            <span asp-validation-for="StatusId" class="text-danger"></span>
        </select>
    </div>

    <button type="submit" class="btn btn-primary is-submit-button">Add</button>
    <a asp-action="Index" class="btn btn-primary">Cancel</a>
</form>

Views/Home/Index.cshtml
@model IEnumerable<Ticket>
@await Component.InvokeAsync("StatusButton", Status.ToDo)
@await Component.InvokeAsync("StatusButton", Status.InProgress)
@await Component.InvokeAsync("StatusButton", Status.QualityAssurance)
@await Component.InvokeAsync("StatusButton", Status.Done)


@{
    string Overdue(Ticket task) => task.Overdue ? "bg-warning" : "";
}

<div class="row">
    <div class="col-sm-2">
        <form asp-action="Filter" method="post">
            
            <div class="form-group">
                <label>Due Date:</label>
                <select name="filter" class="form-control" asp-items="@(new SelectList(ViewBag.DueFilters, "Key", "Value", ViewBag.Filters.Due))">
                    <option value="all">All</option>
                </select>
            </div>
            <div class="form-group">
                <label>Status:</label>
                <select name="filter" class="form-control" asp-items="@(new SelectList(ViewBag.Statuses, "StatusId", "Name", ViewBag.Filters.StatusId))">
                    <option value="all">All</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
            <a asp-action="Index" asp-route-id="" class="btn btn-primary">Clear</a>
        </form>
    </div>
    <div class="col-sm-10">
        <a asp-action="Add"><b>Add New Ticket</b></a>
        <table class="table table-bordered table-striped mt-2">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Sprint Number</th>
                    <th>Point Value</th>
                    <th>Due Date</th>
                    <th>Status</th>
                    <th class="w-25"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Ticket task in Model)
                {
                    string overdue = Overdue(task);
                    <tr>
                        <td>@task.Name</td>
                        <td>@task.Description</td>
                        <td>@task.SprintNumber</td>
                        <td>@task.PointValue</td>
                        <td class="@overdue">
                            @task.DueDate?.ToShortDateString()
                        </td>
                        <td class="@overdue">@task.Status.Name</td>
                        <td>
                            <form asp-action="Edit" method="post"
                                  asp-route-id="@ViewBag.Filters.FilterString" class="mr-2">
                                <input type="hidden" name="@nameof(Ticket.Id)" value="@task.Id" />
                                <button type="submit" name="@nameof(Ticket.StatusId)" value="done" class="btn btn-primary is-submit-button btn-sm">Completed</button>
                                <button type="submit" class="btn btn-primary btn-sm">Delete</button>
                            </form>
                        </td>
                        <td>
                            <form asp-action="ChangeStatus" method="post">
                                <input type="hidden" name="@nameof(Ticket.Id)" value="@task.Id" />
                                <button type="submit" name="@nameof(Ticket.StatusId)" value="todo" class="btn btn-info is-submit-button btn-sm">Set ToDo</button>
                                <button type="submit" name="@nameof(Ticket.StatusId)" value="inprogress" class="btn btn-warning is-submit-button btn-sm">Set In Progress</button>
                                <button type="submit" name="@nameof(Ticket.StatusId)" value="qa" class="btn btn-secondary is-submit-button btn-sm">Set QA</button>
                                <button type="submit" name="@nameof(Ticket.StatusId)" value="done" class="btn btn-success is-submit-button btn-sm">Set Done</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/Components/StatusButton/Default.cshtml
@model TicketToDo.Status

<button class="btn @GetStatusButtonClass(Model)">@Model.ToString()</button>

Views/Shared/Components/StatusButton/Done.cshtml
@model TicketToDo.Status

<button class="btn btn-success @GetStatusButtonClass(Model)">@Model.ToString()</button>

Views/Shared/Components/StatusButton/InProgress.cshtml
@model TicketToDo.Status

<button class="btn btn-warning @GetStatusButtonClass(Model)">@Model.ToString()</button>

Views/Shared/Components/StatusButton/QualityAssurance.cshtml
@model TicketToDo.Status

<button class="btn btn-info @GetStatusButtonClass(Model)">@Model.ToString()</button>

Views/Shared/Components/StatusButton/ToDo.cshtml
@model TicketToDo.Status

<button class="btn btn-primary @GetStatusButtonClass(Model)">@Model.ToString()</button>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Tickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TicketToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <header class="bg-primary text-white text-center">
            <h1 class="m-3 p-3">Tickets</h1>
        </header>
        <main>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>